on:push:branches: [ "main" ]
  pull_request:branches: [ "main" ]

jobs:build:runs-on:windows-lateststrategy:fail-fast:falsematrix:os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        cpp_compiler: [cl]

    steps:-uses:actions/checkout@v3-name:InstallVulkanSDKuses:humbletim/install-vulkan-sdk@v1.1.1with:version:1.3.275.0cache:true-name:Setreusablestringsid:stringsshell:bashrun:|
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
-name:ConfigureCMakerun:>
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -G "Visual Studio 16 2019"
        -A x64
        -S ${{ github.workspace }}
-name:Buildrun:cmake--build${{steps.strings.outputs.build-output-dir}}--config${{matrix.build_type}}-name:Testworking-directory:${{steps.strings.outputs.build-output-dir}}run:ctest--build-config${{matrix.build_type}}-name:UploadBuildArtifactuses:actions/upload-artifact@v3with:name:build-artifactpath:${{steps.strings.outputs.build-output-dir}}
